# Generated by Django 4.2.4 on 2023-08-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'standard')], default=2, max_length=50, verbose_name='user type'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='user',
        ),
    ]
