# Generated by Django 4.2.4 on 2023-08-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='0882652572', max_length=30, verbose_name='phone'),
            preserve_default=False,
        ),
    ]
