# Generated by Django 4.2.4 on 2023-08-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_options_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('2', 'standard'), ('1', 'admin')], default='2', max_length=50, verbose_name='user type'),
        ),
    ]
